name: isbm2021hack
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - nodejs
  - python>=3.7
  - numpy=1.19
  - scipy
  - matplotlib
  - scikit-learn
  - seaborn
  - snakemake-minimal

